### ISSUE TITLE
Memory not freed

### ISSUE THREAD

**Issue by arya2004** [DILPREET1910/CLI-based-todo-list-in-C#1]
The `createTodo()` function allocates memory for the todo list using `malloc`, but there's no corresponding `free` function to release the memory when the program exits. It's essential to free allocated memory before exiting the program to prevent memory leaks.

**Comment by DILPREET1910** [comment]
This project was completed as part of my college's data structure subject in C language, with topics assigned by our professors. We didn't have the option to choose those topics; it was compulsory to create a GitHub repo and keep it public. While I'm not particularly proud of this project, I don't believe it merits further time investment for upgrading. However, you are welcome to fork the repository and apply any changes you see fit and create a pull request. I will make sure to merge it.
Thanks
